### ISSUE TITLE
글 작성 및 저장, 불러오기 기능 구현

### ISSUE THREAD

**Issue by insd47** [ApptiveDev/apptive-19th-hjfund-frontend#6]
## Description
Lexical 프레임워크를 이용하여 Notion과 비슷한 UX를 구현하는 Editor 컴포넌트를 작성합니다.

## To-Do
- [x] 레이아웃 작성하기
- [x] 커맨드 팝업, 인라인 도구 구현
- [x] 블록 및 인라인 스타일 구현
- [ ] 텍스트 색 지정 기능 구현
- [x] 링크 삽입 기능 구현
- [x] 사진 업로드 기능 구현
- [x] 자동 저장 기능 구현
- [ ] 노드 순서 변경 기능 구현
- [ ] 단축키 및 접근성 기능 구현

**Comment by insd47** [comment]
노드 순서 변경 기능, 텍스트 색 지정 기능 등은 백엔드 연동 시작 후 마무리하겠음.
