### ISSUE TITLE
디자인 수정안 반영하기

### ISSUE THREAD

**Issue by insd47** [ApptiveDev/apptive-19th-hjfund-frontend#8]
## Description
목요일에 추가 작업 예정 (취소됨)

## To-Do
- [x] 로고 변경 및 빠진 부분 적용하기
- [x] 브랜드 컬러 적용하기
- [x] 마이페이지 탭 인디케이터 두께 수정
- [x] 마이페이지 투자노트 박스 크기가 알맞지 않은 문제 수정
- [x] 체크박스 효과가 비정상적으로 긴 문제 수정
